[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["...", "php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "nodejs-18_x", "npm"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache"
]

[phases.deploy]
cmds = [
    "php artisan migrate --force",
    "php artisan storage:link"
]
